name: 'Containerized Test Runner For AWS Lambda'
description: 'Run Containerized Tests For AWS Lambda'
author: 'Maxime David <maxday@amazon.com>'

inputs:
  dockerImageName:
    description: 'Name of the image'
    required: true
  taskFolder:
    description: 'Task folder'
    required: true
  suiteFileArray:
    description: 'Array of suite files'
    required: true
  driver:
    description: 'Driver to use'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        pwd
        echo $GITHUB_ACTION_PATH
        ls -lah
        cd $GITHUB_ACTION_PATH
        python -m pip install --upgrade pip
        pip install .
    
    - name: Run test
      shell: bash
      run: |
        pwd
        ls -lah
        python $GITHUB_ACTION_PATH/run.py
      env:
        INPUT_SUITE_FILE_ARRAY: ${{ inputs.suiteFileArray }}
        DOCKER_IMAGE_NAME: ${{ inputs.dockerImageName }}
        TASK_FOLDER: ${{ inputs.taskFolder }}
        DRIVER: ${{ inputs.driver }}
