name: GitHub Action test 

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: codebuild-containerized-test-runner-for-aws-lambda-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          dnf install -y git \
            gcc \
            zlib-devel \
            bzip2-devel \
            readline-devel \
            sqlite-devel \
            openssl-devel \
            xz-devel \
            libffi-devel \
            python-devel
  
    - name: Install python
      run: |
        rm -rf /root/.pyenv
        curl https://pyenv.run | bash
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv install 3.11
        pyenv global 3.11
        ln -sf $(pyenv which python3.11) /usr/local/bin/python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"
        pip install .

    - name: Use the current version of the GitHub action (Python) with wild card
      uses: ./
      with:
        suiteFileArray: '["./github-action-test/lambda/suite*.json"]'
        dockerImageName: 'public.ecr.aws/lambda/python:3.13'
        taskFolder: './github-action-test/lambda/tasks/python'

    - name: Clean up __pycache__ between runs to prevent side effects and start in a clean state
      run: sudo find $GITHUB_WORKSPACE -type d -name __pycache__ -exec rm -rf {} +

    - name: Use the current version of the GitHub action (Python)
      uses: ./
      with:
        suiteFileArray: '["./github-action-test/lambda/suite0.json", "./github-action-test/lambda/suite1.json"]'
        dockerImageName: 'public.ecr.aws/lambda/python:3.13'
        taskFolder: './github-action-test/lambda/tasks/python'

    - name: Clean up __pycache__ between runs to prevent side effects and start in a clean state
      run: sudo find $GITHUB_WORKSPACE -type d -name __pycache__ -exec rm -rf {} +
  
    - name: Use the current version of the GitHub action (NodeJS)
      uses: ./
      with:
        suiteFileArray: '["./github-action-test/lambda/suite0.json"]'
        dockerImageName: 'public.ecr.aws/lambda/nodejs:22'
        taskFolder: './github-action-test/lambda/tasks/nodejs'

    - name: Clean up __pycache__ between runs to prevent side effects and start in a clean state
      run: sudo find $GITHUB_WORKSPACE -type d -name __pycache__ -exec rm -rf {} +

    - name: Pull the image
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/webapp-testing:latest
    - name: Use the current version of the GitHub action (Webapp)
      uses: ./
      with:
        suiteFileArray: '["./github-action-test/webapp/suite_happy_path.json", "./github-action-test/webapp/suite_error.json"]'
        dockerImageName: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/webapp-testing:latest
        taskFolder: './github-action-test/webapp/tasks'
        driver: DockerWebAppDriver


        
